version: '3.8'

services:
  pa11y-dashboard:
    image: node:16
    container_name: pa11y-dashboard
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      PORT: 4000
      MONGO_URL: mongodb://mongodb:27017/pa11y
      WEBSERVICE: http://localhost:3000
    command: ["npm", "start"]

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
