version: '3'

services:
  mongodb:
    image: mongo:6.0
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: always

  pa11y-dashboard:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - PORT=4000
      - MONGO_URL=mongodb://mongodb:27017/pa11y
    restart: always

volumes:
  mongodb_data:
